# Created with Codex release workflow using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenAI.Codex
PackageVersion: 0.162.0
InstallerType: zip
NestedInstallerType: portable
Commands:
- codex
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: codex-command-runner.exe
  - RelativeFilePath: codex-windows-sandbox-setup.exe
  - RelativeFilePath: codex-x86_64-pc-windows-msvc.exe
    PortableCommandAlias: codex
  InstallerUrl: https://github.com/openai/codex/releases/download/rust-v0.162.0/codex-x86_64-pc-windows-msvc.exe.zip
  InstallerSha256: 46558D62BD36D0A87C8DB11D440C05D2167E1B14E1D8525C6391EA78B50D8CFA
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: BurntSushi.ripgrep.MSVC
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: codex-aarch64-pc-windows-msvc.exe
    PortableCommandAlias: codex
  - RelativeFilePath: codex-command-runner.exe
  - RelativeFilePath: codex-windows-sandbox-setup.exe
  InstallerUrl: https://github.com/openai/codex/releases/download/rust-v0.162.0/codex-aarch64-pc-windows-msvc.exe.zip
  InstallerSha256: 478AD0C68DE9EE9909175E0FD7905BA07A82BAB7ACC3EC547CF3EF5B9A1862EA
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: BurntSushi.ripgrep.MSVC
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
